# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm-deep_cloning"
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Till Schulte-Coerne"]
  s.date = "2012-08-15"
  s.description = "A library that lets you clone objects and object graphs"
  s.email = "till.schulte-coerne@innoq.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "dm-deep_cloning.gemspec",
    "lib/data_mapper/deep_cloning/utilities.rb",
    "lib/dm-deep_cloning.rb",
    "spec/dm-deep_cloning_spec.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/changelog.rake",
    "tasks/ci.rake",
    "tasks/metrics.rake",
    "tasks/spec.rake",
    "tasks/yard.rake",
    "tasks/yardstick.rake"
  ]
  s.homepage = "http://github.com/innoq/dm-deep_cloning"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A deep cloning extension for datamapper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<dm-transactions>, ["~> 1.2.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<data_objects>, ["~> 0.10.6"])
      s.add_development_dependency(%q<do_mysql>, ["~> 0.10.6"])
      s.add_development_dependency(%q<dm-do-adapter>, ["~> 1.2.0"])
      s.add_development_dependency(%q<dm-mysql-adapter>, ["~> 1.2.0"])
      s.add_development_dependency(%q<dm-migrations>, ["~> 1.2.0"])
      s.add_development_dependency(%q<dm-timestamps>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.0"])
      s.add_runtime_dependency(%q<dm-transactions>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 1.2.9"])
      s.add_development_dependency(%q<dm-migrations>, ["~> 1.2.9"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-transactions>, ["~> 1.2.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<data_objects>, ["~> 0.10.6"])
      s.add_dependency(%q<do_mysql>, ["~> 0.10.6"])
      s.add_dependency(%q<dm-do-adapter>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-mysql-adapter>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-migrations>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-timestamps>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-core>, ["~> 1.0"])
      s.add_dependency(%q<dm-transactions>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, ["~> 1.2.9"])
      s.add_dependency(%q<dm-migrations>, ["~> 1.2.9"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-transactions>, ["~> 1.2.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.4"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<data_objects>, ["~> 0.10.6"])
    s.add_dependency(%q<do_mysql>, ["~> 0.10.6"])
    s.add_dependency(%q<dm-do-adapter>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-mysql-adapter>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-migrations>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-timestamps>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-core>, ["~> 1.0"])
    s.add_dependency(%q<dm-transactions>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, ["~> 1.2.9"])
    s.add_dependency(%q<dm-migrations>, ["~> 1.2.9"])
  end
end

